#!/usr/bin/env bash

#Update package index and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/.*listen\(.*\)80;/' /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html 

sudo service nginx restart