#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header

#Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Add custom HTTP response header configuration
echo 'server_tokens off;' >> /etc/nginx/nginx.conf
echo "add_header X-Served-By \$hostname;" >> /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemcl restart nginx
