#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

dump_file="backup.sql"
archive_name="$(date +'%d-%m-%Y').tar.gz"
mysql_password="$1"

#generate MySQL dump
mysqldump -u root -p"$mysql_password" --all-databases > "$dump_file"

#compress the MySQL dump into a tar.gz archive
tar -czvf "$archive_name" "$dump_file"
